/**
 * Converts scripts/linkedin-articles.json into:
 *   src/data/archive.ts  — Newsletter[] for all scraped LinkedIn editions
 *
 * Run after scrape-linkedin.mjs:
 *   node scripts/generate-archive.mjs
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const INPUT_FILE = join(__dirname, 'linkedin-articles.json');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'data', 'archive.ts');

const articles = JSON.parse(readFileSync(INPUT_FILE, 'utf8'));

const successful = articles.filter(a => !a.failed && a.html);
const failed = articles.filter(a => a.failed || !a.html);

console.log(`Processing ${successful.length} successful articles (${failed.length} failed/empty)`);

// Infer a tag from the title / content
function inferTag(article) {
  const text = (article.title + ' ' + (article.excerpt || '')).toLowerCase();
  if (text.includes('ai ') || text.includes('artificial intelligence') || text.includes('agent')) return 'AI & Future of Work';
  if (text.includes('labor market') || text.includes('jobs') || text.includes('unemployment')) return 'Labor Market';
  if (text.includes('talent acquisition') || text.includes('recruiting') || text.includes('hiring')) return 'Talent Acquisition';
  if (text.includes('dei') || text.includes('diversity') || text.includes('inclusion')) return 'DEI';
  if (text.includes('amazon') || text.includes('robot') || text.includes('automation')) return 'Automation';
  if (text.includes('linkedin') || text.includes('social')) return 'Social Media';
  if (text.includes('hr tech') || text.includes('hrtech') || text.includes('vendor')) return 'HR Tech';
  return 'HR Tech';
}

// Escape backticks and ${} in HTML for template literal
function escapeForTemplate(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

let ts = `// Auto-generated by scripts/generate-archive.mjs — DO NOT EDIT MANUALLY
// Run: node scripts/scrape-linkedin.mjs && node scripts/generate-archive.mjs

import type { Newsletter } from './newsletters'

export const archive: Newsletter[] = [
`;

for (const article of successful) {
  const tag = inferTag(article);
  const excerpt = (article.excerpt || '').replace(/'/g, "\\'").slice(0, 250);
  const body = escapeForTemplate(article.html);
  const slug = article.slug;

  ts += `  {
    slug: '${slug}',
    date: '${article.date}',
    title: ${JSON.stringify(article.title)},
    tag: '${tag}',
    excerpt: ${JSON.stringify(article.excerpt?.slice(0, 250) || '')},
    body: \`${body}\`,
  },
`;
}

ts += `];\n`;

writeFileSync(OUTPUT_FILE, ts);
console.log(`✅ Written ${successful.length} articles to ${OUTPUT_FILE}`);

if (failed.length > 0) {
  console.log('\n⚠️  Failed articles (still link to LinkedIn):');
  for (const a of failed) {
    console.log(`  - ${a.date}: ${a.title}`);
    if (a.error) console.log(`    Error: ${a.error}`);
  }
}

console.log('\nNext steps:');
console.log('1. Review src/data/archive.ts');
console.log('2. Run: npm run build to verify no TypeScript errors');
console.log('3. Run: npm run deploy:no-send to go live');
