// AUTO-GENERATED by scripts/discover-ats.mjs — re-run to refresh.
// Hand-edit entries where ats === "unknown" to set the correct handle.
export type VendorAtsMapping = {
  slug: string
  name: string
  ats: 'greenhouse' | 'lever' | 'ashby' | 'smartrecruiters' | 'workable' | 'recruitee' | 'unknown'
  handle: string | null
  careers_url: string | null
  discovery_source: 'sniff' | 'probe' | 'none'
  discovery_job_count: number
}

export const vendorAts: VendorAtsMapping[] = [
  {
    "slug": "workday",
    "name": "Workday",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://workday.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "sap-successfactors",
    "name": "SAP SuccessFactors",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://successfactors.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "oracle-hcm-cloud",
    "name": "Oracle HCM Cloud",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://oracle.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "ukg-pro",
    "name": "UKG Pro",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://ukg.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "ceridian-dayforce",
    "name": "Ceridian Dayforce",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://ceridian.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "paycom",
    "name": "Paycom",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://paycom.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "paychex-flex",
    "name": "Paychex Flex",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://paychex.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "infor-hcm",
    "name": "Infor HCM",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://infor.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "darwinbox",
    "name": "Darwinbox",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://darwinbox.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "namely",
    "name": "Namely",
    "ats": "smartrecruiters",
    "handle": "namely",
    "careers_url": "https://namely.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 1
  },
  {
    "slug": "greenhouse",
    "name": "Greenhouse",
    "ats": "greenhouse",
    "handle": "greenhouse",
    "careers_url": "https://greenhouse.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 32
  },
  {
    "slug": "lever",
    "name": "Lever",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://lever.co/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "icims",
    "name": "iCIMS",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://icims.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "ashby",
    "name": "Ashby",
    "ats": "ashby",
    "handle": "ashby",
    "careers_url": "https://ashbyhq.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 60
  },
  {
    "slug": "smartrecruiters",
    "name": "SmartRecruiters",
    "ats": "smartrecruiters",
    "handle": "smartrecruiters",
    "careers_url": "https://smartrecruiters.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 1
  },
  {
    "slug": "workable",
    "name": "Workable",
    "ats": "workable",
    "handle": "careers",
    "careers_url": "https://workable.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 8
  },
  {
    "slug": "jazzhr",
    "name": "JazzHR",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://jazzhr.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "bullhorn",
    "name": "Bullhorn",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://bullhorn.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "breezy-hr",
    "name": "Breezy HR",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://breezy.hr/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "oracle-taleo",
    "name": "Oracle Taleo",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://oracle.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "bamboohr",
    "name": "BambooHR",
    "ats": "recruitee",
    "handle": "bamboohr",
    "careers_url": "https://bamboohr.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 2
  },
  {
    "slug": "rippling",
    "name": "Rippling",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://rippling.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "gusto",
    "name": "Gusto",
    "ats": "greenhouse",
    "handle": "gusto",
    "careers_url": "https://gusto.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 87
  },
  {
    "slug": "zenefits",
    "name": "Zenefits",
    "ats": "smartrecruiters",
    "handle": "zenefits",
    "careers_url": "https://zenefits.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 1
  },
  {
    "slug": "personio",
    "name": "Personio",
    "ats": "recruitee",
    "handle": "personio",
    "careers_url": "https://personio.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 1
  },
  {
    "slug": "hibob",
    "name": "HiBob",
    "ats": "smartrecruiters",
    "handle": "hibob",
    "careers_url": "https://hibob.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 1
  },
  {
    "slug": "factorial",
    "name": "Factorial",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://factorialhr.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "deel",
    "name": "Deel",
    "ats": "ashby",
    "handle": "deel",
    "careers_url": "https://deel.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 265
  },
  {
    "slug": "humaans",
    "name": "Humaans",
    "ats": "ashby",
    "handle": "humaans",
    "careers_url": "https://humaans.io/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 14
  },
  {
    "slug": "sage-hr",
    "name": "Sage HR",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://sage.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "adp",
    "name": "ADP",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://adp.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "paychex",
    "name": "Paychex",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://paychex.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "paylocity",
    "name": "Paylocity",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://paylocity.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "onpay",
    "name": "OnPay",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://onpay.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "homebase",
    "name": "Homebase",
    "ats": "ashby",
    "handle": "homebase",
    "careers_url": "https://joinhomebase.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 22
  },
  {
    "slug": "quickbooks-payroll",
    "name": "QuickBooks Payroll",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://intuit.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "patriot-software",
    "name": "Patriot Software",
    "ats": "workable",
    "handle": "patriot-software",
    "careers_url": "https://patriotsoftware.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 0
  },
  {
    "slug": "remote",
    "name": "Remote",
    "ats": "greenhouse",
    "handle": "remotecom",
    "careers_url": "https://remote.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 21
  },
  {
    "slug": "papaya-global",
    "name": "Papaya Global",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://papayaglobal.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "wagepoint",
    "name": "Wagepoint",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://wagepoint.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "lattice",
    "name": "Lattice",
    "ats": "greenhouse",
    "handle": "lattice",
    "careers_url": "https://lattice.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 16
  },
  {
    "slug": "15five",
    "name": "15Five",
    "ats": "lever",
    "handle": "15five",
    "careers_url": "https://15five.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 7
  },
  {
    "slug": "culture-amp",
    "name": "Culture Amp",
    "ats": "greenhouse",
    "handle": "cultureamp",
    "careers_url": "https://cultureamp.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 25
  },
  {
    "slug": "betterworks",
    "name": "Betterworks",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://betterworks.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "leapsome",
    "name": "Leapsome",
    "ats": "ashby",
    "handle": "Leapsome",
    "careers_url": "https://leapsome.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 13
  },
  {
    "slug": "engagedly",
    "name": "Engagedly",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://engagedly.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "reflektive",
    "name": "Reflektive",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://reflektive.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "performyard",
    "name": "PerformYard",
    "ats": "workable",
    "handle": "performyard",
    "careers_url": "https://performyard.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 7
  },
  {
    "slug": "trakstar",
    "name": "Mitratech (Trakstar)",
    "ats": "greenhouse",
    "handle": "mitratech",
    "careers_url": "https://trakstar.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 34
  },
  {
    "slug": "workboard",
    "name": "WorkBoard",
    "ats": "greenhouse",
    "handle": "workboard",
    "careers_url": "https://workboard.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 7
  },
  {
    "slug": "cornerstone-ondemand",
    "name": "Cornerstone OnDemand",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://cornerstoneondemand.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "docebo",
    "name": "Docebo",
    "ats": "ashby",
    "handle": "docebo",
    "careers_url": "https://docebo.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 50
  },
  {
    "slug": "talentlms",
    "name": "TalentLMS",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://talentlms.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "absorb-lms",
    "name": "Absorb LMS",
    "ats": "ashby",
    "handle": "absorblms",
    "careers_url": "https://absorblms.com/careers",
    "discovery_source": "sniff",
    "discovery_job_count": 24
  },
  {
    "slug": "sap-litmos",
    "name": "SAP Litmos",
    "ats": "greenhouse",
    "handle": "litmos",
    "careers_url": "https://litmos.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 13
  },
  {
    "slug": "360learning",
    "name": "360Learning",
    "ats": "lever",
    "handle": "360learning",
    "careers_url": "https://360learning.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 39
  },
  {
    "slug": "linkedin-learning",
    "name": "LinkedIn Learning",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://linkedin.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "degreed",
    "name": "Degreed",
    "ats": "greenhouse",
    "handle": "degreed",
    "careers_url": "https://degreed.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 4
  },
  {
    "slug": "seismic-learning",
    "name": "Seismic Learning",
    "ats": "workable",
    "handle": "seismic",
    "careers_url": "https://seismic.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 3
  },
  {
    "slug": "bridge-lms",
    "name": "Bridge LMS",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://bridgeapp.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "visier",
    "name": "Visier",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://visier.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "workday-prism",
    "name": "Workday Prism",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://workday.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "sap-people-analytics",
    "name": "SAP People Analytics",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://successfactors.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "orgvue",
    "name": "OrgVue",
    "ats": "workable",
    "handle": "orgvue",
    "careers_url": "https://orgvue.com/careers",
    "discovery_source": "probe",
    "discovery_job_count": 21
  },
  {
    "slug": "crunchr",
    "name": "Crunchr",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://crunchr.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "peakon",
    "name": "Peakon",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://peakon.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "perceptyx",
    "name": "Perceptyx",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://perceptyx.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "qualtrics-employeexm",
    "name": "Qualtrics EmployeeXM",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://qualtrics.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "medallia",
    "name": "Medallia",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://medallia.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  },
  {
    "slug": "revelio-labs",
    "name": "Revelio Labs",
    "ats": "unknown",
    "handle": null,
    "careers_url": "https://reveliolabs.com/careers",
    "discovery_source": "none",
    "discovery_job_count": 0
  }
]
